name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace Account ID
      run: |
        sed 's/REPLACE_WITH_ACCOUNT_ID/${{ secrets.CF_ACCOUNT_ID }}/' wrangler.template.toml > wrangler.toml

    - name: Install Latest Wrangler
      run: npm install -g wrangler

    - name: Publish to Cloudflare
      run: wrangler deploy
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}